/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.inheritance;

public class Library {
    public static void main(String[] args) {
        Restaurant r1 = new Restaurant("res1",2,2.5);
        System.out.println(r1);


        Review review = new Review("good","Alaa",4);
        Review review1 = new Review("bad","Alaa",7);
        r1.addReview(review);
        r1.addReview(review1);
        System.out.println(r1.getLists());

        System.out.println(r1);
        Shop shop1 = new Shop("A1shop","animal shops",5);
        Review rev1 = new Review("bad","alaa",20);
        Review rev2 = new Review("good","alaa2",4);

            shop1.addReview(rev1);
            shop1.addReview(rev2);
            System.out.println(shop1.getlist());
            System.out.println(shop1);

        Theater th1 =new Theater("Mov1");
        th1.addMovie("Movies1");
        th1.addMovie("Movie2");
        System.out.println(th1.getMovies());
        System.out.println(th1);


       // test remove
        Theater th2 =new Theater("Mov2");
        th2.addMovie("Movie1");
        th2.addMovie("Movie2");
        System.out.println(th2.getMovies());
        System.out.println(th2);

       // th2.removeMovie("Movie2");
        System.out.println(th2.getMovies());
        System.out.println(th2);



        th2.addRev("bad","AAA",5);
        Review r3 = new Review("good","ALaa",5);
        th2.addRev(r3,"Movie1");
        th2.addRev(r3,"Movie2");
        System.out.println(th2);
        System.out.println(th2.getReviews());
    }



    public boolean someLibraryMethod() {
        return true;
    }
}
