/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.inheritance;

import main.java.inheritance.*;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {

    Restaurant R1 = new Restaurant("Alaa",2,2.5);
    Review review = new Review("good","Alaa",2);
     Shop shop1 = new Shop("A1shop","animal shops",5);


    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test
    public void testRestaurantCon() {
      assertEquals("Alaa",R1.getName());
      assertEquals(2.5,R1.getStars(),2.5);
      assertEquals(2.5,R1.getPrice(),2.5);
    }
    @Test
    public void testToStringRes() {
        assertEquals("Restaurant{Name='Alaa', rate=2.5, price=2.5}",R1.toString());
    }

    @Test
    public void testReviewCon() {
        assertEquals("good",review.getBody());
        assertEquals("Alaa",review.getAuthor());
        assertEquals(2,review.getStars());
    }

    @Test
    public void testToStringRev() {
        assertEquals("Review{body='good', author='Alaa', numStars=2}",review.toString());
    }

    @Test
    public void testShopCon() {

      assertEquals("A1shop",shop1.getName());
        assertEquals("animal shops",shop1.getDescription());
        assertEquals(5,shop1.getNumberOfSings());
    }

    @Test
    public void testToTheater() {
        Theater movie = new Theater("Alaa");
        assertEquals("Theater{name='Alaa', movies[], reviews={}}",String.valueOf(movie));
    }
}
